const resources = {
  en: {
    translation: {
      "stage_start_title": "Dive into a world of mysteries and adventures with our narrative exploration game, where you are the hero! By making choices at each stage, you’ll guide the main character through puzzles, trials, and captivating quests in mystical locations.",
      "stage_start_subtitle": "Good luck!",
      "stage_start_button": "Start",
      "feedback_q1": "How was the story?",
      "feedback_q2": "How was the character?",
      "feedback_q3": "Any other feedbacks?",
      "feedback_q3_placeholder": "Please share your thoughts and suggestions here...",
      "feedback_email": "Your email:",
      "feedback_submit": "Play Again",
      "end_story": "End story",
      "credits": "(The story is generated by an AI)",
      "credits_title": "Credits",
      "credits_message1": "The story is generated by an AI.",
      "credits_message2": "The web application is developed under React and with the UI of Chakra-UI.",
      "credits_message3": "This application is developed by Valentin RUDLOFF."
    }
  },
  fr: {
    translation: {
      "stage_start_title": "Plongez dans un monde de mystères et d’aventures avec ce jeu d’exploration narratif, où vous êtes le héros ! En faisant vos choix à chaque étape, vous guiderez le personnage principal à travers des énigmes, des épreuves et des quêtes fascinantes dans des lieux mystiques.",
      "stage_start_subtitle": "Bonne chance !",
      "stage_start_button": "Commencer",
      "feedback_q1": "Comment était la histoire?",
      "feedback_q2": "Comment était le personnage?",
      "feedback_q3": "D'autres commentaires?",
      "feedback_q3_placeholder": "Veuillez partager vos pensées et suggestions ici...",
      "feedback_email": "Votre email:",
      "feedback_submit": "Rejouer",
      "end_story": "Finir la partie",
      "credits_title": "Crédits",
      "credits_message1": "L'histoire est générée par ChatGPT de OpenAI.",
      "credits_message2": "Application web développée sous React et avec les UI de Chakra-UI.",
      "credits_message3": "Cette application a été développée par Valentin RUDLOFF."
    }
  }
};

export default resources;